
import { Subject } from './types';

export const SYLLABUS_DATA: Subject[] = [
  {
    id: 'algorithms',
    name: 'Algorithms',
    totalWeight: 318,
    topics: [
      { id: '1.1', name: 'Algorithm Design', weight: 8, completed: false },
      { id: '1.2', name: 'Algorithm Design Technique', weight: 9, completed: false },
      { id: '1.3', name: 'Asymptotic Notation', weight: 21, completed: false },
      { id: '1.4', name: 'Bellman Ford', weight: 2, completed: false },
      { id: '1.5', name: 'Binary Search', weight: 2, completed: false },
      { id: '1.6', name: 'Dijkstras Algorithm', weight: 6, completed: false },
      { id: '1.7', name: 'Dynamic Programming', weight: 9, completed: false },
      { id: '1.8', name: 'Graph Algorithms', weight: 11, completed: false },
      { id: '1.9', name: 'Graph Search', weight: 22, completed: false },
      { id: '1.10', name: 'Greedy Algorithm', weight: 5, completed: false },
      { id: '1.11', name: 'Hashing', weight: 7, completed: false },
      { id: '1.12', name: 'Huffman Code', weight: 6, completed: false },
      { id: '1.13', name: 'Identify Function', weight: 38, completed: false },
      { id: '1.14', name: 'Insertion Sort', weight: 2, completed: false },
      { id: '1.15', name: 'Matrix Chain Ordering', weight: 3, completed: false },
      { id: '1.16', name: 'Merge Sort', weight: 3, completed: false },
      { id: '1.17', name: 'Merging', weight: 2, completed: false },
      { id: '1.18', name: 'Minimum Spanning Tree', weight: 33, completed: false },
      { id: '1.19', name: 'Prims Algorithm', weight: 2, completed: false },
      { id: '1.20', name: 'Quick Sort', weight: 14, completed: false },
      { id: '1.21', name: 'Recurrence Relation', weight: 34, completed: false },
      { id: '1.22', name: 'Recursion', weight: 4, completed: false },
      { id: '1.23', name: 'Searching', weight: 6, completed: false },
      { id: '1.24', name: 'Shortest Path', weight: 5, completed: false },
      { id: '1.25', name: 'Sorting', weight: 27, completed: false },
      { id: '1.26', name: 'Space Complexity', weight: 1, completed: false },
      { id: '1.27', name: 'Strongly Connected Components', weight: 3, completed: false },
      { id: '1.28', name: 'Time Complexity', weight: 29, completed: false },
      { id: '1.29', name: 'Topological Sort', weight: 4, completed: false },
    ],
  },
  {
    id: 'co-architecture',
    name: 'CO and Architecture',
    totalWeight: 228,
    topics: [
      { id: '2.1', name: 'Addressing Modes', weight: 18, completed: false },
      { id: '2.2', name: 'CISC RISC Architecture', weight: 2, completed: false },
      { id: '2.3', name: 'Cache Memory', weight: 71, completed: false },
      { id: '2.4', name: 'DMA', weight: 9, completed: false },
      { id: '2.5', name: 'Data Dependency', weight: 2, completed: false },
      { id: '2.6', name: 'Data Path', weight: 6, completed: false },
      { id: '2.7', name: 'IO Handling', weight: 7, completed: false },
      { id: '2.8', name: 'Instruction Execution', weight: 6, completed: false },
      { id: '2.9', name: 'Instruction Format', weight: 9, completed: false },
      { id: '2.10', name: 'Interrupts', weight: 8, completed: false },
      { id: '2.11', name: 'Machine Instruction', weight: 20, completed: false },
      { id: '2.12', name: 'Memory Interfacing', weight: 6, completed: false },
      { id: '2.13', name: 'Microprogramming', weight: 13, completed: false },
      { id: '2.14', name: 'Pipelining', weight: 42, completed: false },
      { id: '2.15', name: 'Runtime Environment', weight: 2, completed: false },
      { id: '2.16', name: 'Speedup', weight: 4, completed: false },
      { id: '2.17', name: 'Virtual Memory', weight: 3, completed: false },
    ],
  },
  {
    id: 'compiler-design',
    name: 'Compiler Design',
    totalWeight: 226,
    topics: [
        { id: '3.1', name: 'Assembler', weight: 9, completed: false },
        { id: '3.2', name: 'Code Optimization', weight: 9, completed: false },
        { id: '3.3', name: 'Compilation Phases', weight: 12, completed: false },
        { id: '3.4', name: 'Expression Evaluation', weight: 2, completed: false },
        { id: '3.5', name: 'First and Follow', weight: 5, completed: false },
        { id: '3.6', name: 'Grammar', weight: 50, completed: false },
        { id: '3.7', name: 'Intermediate Code', weight: 11, completed: false },
        { id: '3.8', name: 'LR Parser', weight: 19, completed: false },
        { id: '3.9', name: 'Lexical Analysis', weight: 6, completed: false },
        { id: '3.10', name: 'Linker', weight: 3, completed: false },
        { id: '3.11', name: 'Live Variable Analysis', weight: 3, completed: false },
        { id: '3.12', name: 'Macros', weight: 4, completed: false },
        { id: '3.13', name: 'Operator Precedence', weight: 3, completed: false },
        { id: '3.14', name: 'Parameter Passing', weight: 14, completed: false },
        { id: '3.15', name: 'Parsing', weight: 27, completed: false },
        { id: '3.16', name: 'Register Allocation', weight: 6, completed: false },
        { id: '3.17', name: 'Runtime Environment', weight: 22, completed: false },
        { id: '3.18', name: 'Static Single Assignment', weight: 3, completed: false },
        { id: '3.19', name: 'Syntax Directed Translation', weight: 16, completed: false },
        { id: '3.20', name: 'Variable Scope', weight: 2, completed: false },
    ]
  },
  {
    id: 'computer-networks',
    name: 'Computer Networks',
    totalWeight: 205,
    topics: [
        { id: '4.1', name: 'Application Layer Protocols', weight: 12, completed: false },
        { id: '4.2', name: 'Bit Stuffing', weight: 2, completed: false },
        { id: '4.3', name: 'Bridges', weight: 3, completed: false },
        { id: '4.4', name: 'CRC Polynomial', weight: 4, completed: false },
        { id: '4.5', name: 'CSMA CD', weight: 5, completed: false },
        { id: '4.6', name: 'Communication', weight: 4, completed: false },
        { id: '4.7', name: 'Congestion Control', weight: 7, completed: false },
        { id: '4.8', name: 'Distance Vector Routing', weight: 8, completed: false },
        { id: '4.9', name: 'Error Detection', weight: 10, completed: false },
        { id: '4.10', name: 'Ethernet', weight: 7, completed: false },
        { id: '4.11', name: 'IP Addressing', weight: 10, completed: false },
        { id: '4.12', name: 'IP Packet', weight: 11, completed: false },
        { id: '4.13', name: 'LAN Technologies', weight: 7, completed: false },
        { id: '4.14', name: 'MAC Protocol', weight: 5, completed: false },
        { id: '4.15', name: 'Network Flow', weight: 4, completed: false },
        { id: '4.16', name: 'Network Layering', weight: 6, completed: false },
        { id: '4.17', name: 'Network Protocols', weight: 10, completed: false },
        { id: '4.18', name: 'Network Switching', weight: 4, completed: false },
        { id: '4.19', name: 'Routing', weight: 13, completed: false },
        { id: '4.20', name: 'Sliding Window', weight: 15, completed: false },
        { id: '4.21', name: 'Sockets', weight: 4, completed: false },
        { id: '4.22', name: 'Stop and Wait', weight: 6, completed: false },
        { id: '4.23', name: 'Subnetting', weight: 20, completed: false },
        { id: '4.24', name: 'TCP', weight: 21, completed: false },
        { id: '4.25', name: 'Token Bucket', weight: 2, completed: false },
        { id: '4.26', name: 'UDP', weight: 4, completed: false },
    ]
  },
   {
    id: 'databases',
    name: 'Databases',
    totalWeight: 268,
    topics: [
        { id: '5.1', name: 'B Tree', weight: 29, completed: false },
        { id: '5.2', name: 'Candidate Key', weight: 5, completed: false },
        { id: '5.3', name: 'Conflict Serializable', weight: 8, completed: false },
        { id: '5.4', name: 'Database Design', weight: 1, completed: false },
        { id: '5.5', name: 'Database Normalization', weight: 55, completed: false },
        { id: '5.6', name: 'ER Diagram', weight: 12, completed: false },
        { id: '5.7', name: 'Indexing', weight: 13, completed: false },
        { id: '5.8', name: 'Joins', weight: 7, completed: false },
        { id: '5.9', name: 'Multivalued Dependency 4nf', weight: 1, completed: false },
        { id: '5.10', name: 'Natural Join', weight: 3, completed: false },
        { id: '5.11', name: 'Query', weight: 1, completed: false },
        { id: '5.12', name: 'Referential Integrity', weight: 5, completed: false },
        { id: '5.13', name: 'Relational Algebra', weight: 29, completed: false },
        { id: '5.14', name: 'Relational Calculus', weight: 15, completed: false },
        { id: '5.15', name: 'Relational Model', weight: 1, completed: false },
        { id: '5.16', name: 'SQL', weight: 55, completed: false },
        { id: '5.17', name: 'Transaction and Concurrency', weight: 28, completed: false },
    ]
  },
  {
    id: 'digital-logic',
    name: 'Digital Logic',
    totalWeight: 292,
    topics: [
        { id: '6.1', name: 'Adder', weight: 9, completed: false },
        { id: '6.2', name: 'Array Multiplier', weight: 2, completed: false },
        { id: '6.3', name: 'Boolean Algebra', weight: 32, completed: false },
        { id: '6.4', name: 'Booths Algorithm', weight: 6, completed: false },
        { id: '6.5', name: 'Canonical Normal Form', weight: 9, completed: false },
        { id: '6.6', name: 'Carry Generator', weight: 2, completed: false },
        { id: '6.7', name: 'Circuit Output', weight: 39, completed: false },
        { id: '6.8', name: 'Combinational Circuit', weight: 2, completed: false },
        { id: '6.9', name: 'Decoder', weight: 3, completed: false },
        { id: '6.10', name: 'Digital Circuits', weight: 6, completed: false },
        { id: '6.11', name: 'Digital Counter', weight: 17, completed: false },
        { id: '6.12', name: 'Finite State Machines', weight: 4, completed: false },
        { id: '6.13', name: 'Fixed Point Representation', weight: 2, completed: false },
        { id: '6.14', name: 'Flip Flop', weight: 6, completed: false },
        { id: '6.15', name: 'Floating Point Representation', weight: 8, completed: false },
        { id: '6.16', name: 'Functional Completeness', weight: 7, completed: false },
        { id: '6.17', name: 'IEEE Representation', weight: 11, completed: false },
        { id: '6.18', name: 'K Map', weight: 19, completed: false },
        { id: '6.19', name: 'Memory Interfacing', weight: 4, completed: false },
        { id: '6.20', name: 'Min No Gates', weight: 4, completed: false },
        { id: '6.21', name: 'Min Product of Sums', weight: 2, completed: false },
        { id: '6.22', name: 'Min Sum of Products Form', weight: 14, completed: false },
        { id: '6.23', name: 'Multiplexer', weight: 14, completed: false },
        { id: '6.24', name: 'Number Representation', weight: 57, completed: false },
        { id: '6.25', name: 'Prime Implicants', weight: 2, completed: false },
        { id: '6.26', name: 'ROM', weight: 4, completed: false },
        { id: '6.27', name: 'Shift Registers', weight: 2, completed: false },
        { id: '6.28', name: 'Static Hazard', weight: 1, completed: false },
        { id: '6.29', name: 'Synchronous Asynchronous Circuits', weight: 4, completed: false },
    ]
  },
  {
    id: 'operating-system',
    name: 'Operating System',
    totalWeight: 326,
    topics: [
        { id: '7.1', name: 'Context Switch', weight: 4, completed: false },
        { id: '7.2', name: 'Deadlock', weight: 4, completed: false },
        { id: '7.3', name: 'Disk', weight: 31, completed: false },
        { id: '7.4', name: 'Disk Scheduling', weight: 14, completed: false },
        { id: '7.5', name: 'File System', weight: 9, completed: false },
        { id: '7.6', name: 'Fork System Call', weight: 7, completed: false },
        { id: '7.7', name: 'IO Handling', weight: 6, completed: false },
        { id: '7.8', name: 'Inter Process Communication', weight: 1, completed: false },
        { id: '7.9', name: 'Interrupts', weight: 7, completed: false },
        { id: '7.10', name: 'Memory Management', weight: 10, completed: false },
        { id: '7.11', name: 'OS Protection', weight: 3, completed: false },
        { id: '7.12', name: 'Page Replacement', weight: 32, completed: false },
        { id: '7.13', name: 'Precedence Graph', weight: 3, completed: false },
        { id: '7.14', name: 'Process', weight: 5, completed: false },
        { id: '7.15', name: 'Process Scheduling', weight: 47, completed: false },
        { id: '7.16', name: 'Process Synchronization', weight: 52, completed: false },
        { id: '7.17', name: 'Resource Allocation', weight: 27, completed: false },
        { id: '7.18', name: 'Semaphore', weight: 10, completed: false },
        { id: '7.19', name: 'System Call', weight: 1, completed: false },
        { id: '7.20', name: 'Threads', weight: 10, completed: false },
        { id: '7.21', name: 'Virtual Memory', weight: 43, completed: false },
    ]
  },
  {
    id: 'programming-ds',
    name: 'Programming and DS',
    totalWeight: 227,
    topics: [
        { id: '8.1', name: 'AVL Tree', weight: 4, completed: false },
        { id: '8.2', name: 'Array', weight: 13, completed: false },
        { id: '8.3', name: 'Binary Heap', weight: 29, completed: false },
        { id: '8.4', name: 'Binary Search Tree', weight: 34, completed: false },
        { id: '8.5', name: 'Binary Tree', weight: 53, completed: false },
        { id: '8.6', name: 'Data Structures', weight: 6, completed: false },
        { id: '8.7', name: 'Hashing', weight: 16, completed: false },
        { id: '8.8', name: 'Infix Prefix', weight: 5, completed: false },
        { id: '8.9', name: 'Linked List', weight: 22, completed: false },
        { id: '8.10', name: 'Priority Queue', weight: 2, completed: false },
        { id: '8.11', name: 'Queue', weight: 13, completed: false },
        { id: '8.12', name: 'Stack', weight: 16, completed: false },
        { id: '8.13', name: 'Tree', weight: 14, completed: false },
    ]
  },
  {
    id: 'programming-c',
    name: 'Programming in C',
    totalWeight: 120,
    topics: [
        { id: '9.1', name: 'Aliasing', weight: 1, completed: false },
        { id: '9.2', name: 'Array', weight: 13, completed: false },
        { id: '9.3', name: 'Functions', weight: 1, completed: false },
        { id: '9.4', name: 'Goto', weight: 2, completed: false },
        { id: '9.5', name: 'Identify Function', weight: 6, completed: false },
        { id: '9.6', name: 'Loop Invariants', weight: 8, completed: false },
        { id: '9.7', name: 'Output', weight: 5, completed: false },
        { id: '9.8', name: 'Parameter Passing', weight: 12, completed: false },
        { id: '9.9', name: 'Pointers', weight: 11, completed: false },
        { id: '9.10', name: 'Programming Constructs', weight: 1, completed: false },
        { id: '9.11', name: 'Programming In C', weight: 31, completed: false },
        { id: '9.12', name: 'Programming Paradigms', weight: 2, completed: false },
        { id: '9.13', name: 'Recursion', weight: 17, completed: false },
        { id: '9.14', name: 'Structure', weight: 5, completed: false },
        { id: '9.15', name: 'Switch Case', weight: 2, completed: false },
        { id: '9.16', name: 'Type Checking', weight: 1, completed: false },
        { id: '9.17', name: 'Union', weight: 1, completed: false },
        { id: '9.18', name: 'Variable Binding', weight: 1, completed: false },
    ]
  },
  {
    id: 'theory-of-computation',
    name: 'Theory of Computation',
    totalWeight: 275,
    topics: [
        { id: '10.1', name: 'Closure Property', weight: 8, completed: false },
        { id: '10.2', name: 'Context Free Language', weight: 32, completed: false },
        { id: '10.3', name: 'Countable Uncountable Set', weight: 3, completed: false },
        { id: '10.4', name: 'Decidability', weight: 29, completed: false },
        { id: '10.5', name: 'Finite Automata', weight: 41, completed: false },
        { id: '10.6', name: 'Identify Class Language', weight: 31, completed: false },
        { id: '10.7', name: 'Minimal State Automata', weight: 25, completed: false },
        { id: '10.8', name: 'Non Determinism', weight: 6, completed: false },
        { id: '10.9', name: 'Pumping Lemma', weight: 2, completed: false },
        { id: '10.10', name: 'Pushdown Automata', weight: 15, completed: false },
        { id: '10.11', name: 'Recursive & RE Languages', weight: 16, completed: false },
        { id: '10.12', name: 'Reduction', weight: 2, completed: false },
        { id: '10.13', name: 'Regular Expression', weight: 29, completed: false },
        { id: '10.14', name: 'Regular Grammar', weight: 3, completed: false },
        { id: '10.15', name: 'Regular Language', weight: 33, completed: false },
    ]
  },
   {
    id: 'discrete-mathematics',
    name: 'Discrete Mathematics',
    totalWeight: 373,
    topics: [
      {id: 'dm.1.1', name: 'Balls In Bins', weight: 4, completed: false},
      {id: 'dm.1.2', name: 'Combinatory', weight: 21, completed: false},
      {id: 'dm.1.3', name: 'Counting', weight: 4, completed: false},
      {id: 'dm.1.4', name: 'Generating Functions', weight: 6, completed: false},
      {id: 'dm.1.5', name: 'Modular Arithmetic', weight: 2, completed: false},
      {id: 'dm.1.6', name: 'Pigeonhole Principle', weight: 2, completed: false},
      {id: 'dm.1.7', name: 'Recurrence Relation', weight: 7, completed: false},
      {id: 'dm.1.8', name: 'Summation', weight: 3, completed: false},
      {id: 'dm.2.1', name: 'Graph Counting', weight: 3, completed: false},
      {id: 'dm.2.2', name: 'Degree of Graph', weight: 12, completed: false},
      {id: 'dm.2.3', name: 'Graph Coloring', weight: 11, completed: false},
      {id: 'dm.2.4', name: 'Graph Connectivity', weight: 40, completed: false},
      {id: 'dm.2.5', name: 'Graph Isomorphism', weight: 1, completed: false},
      {id: 'dm.2.6', name: 'Graph Matching', weight: 1, completed: false},
      {id: 'dm.2.7', name: 'Graph Planarity', weight: 13, completed: false},
      {id: 'dm.3.1', name: 'First Order Logic', weight: 32, completed: false},
      {id: 'dm.3.2', name: 'Logical Reasoning', weight: 3, completed: false},
      {id: 'dm.3.3', name: 'Propositional Logic', weight: 40, completed: false},
      {id: 'dm.4.1', name: 'Binary Operation', weight: 8, completed: false},
      {id: 'dm.4.2', name: 'Countable Uncountable Set', weight: 2, completed: false},
      {id: 'dm.4.3', name: 'Functions', weight: 29, completed: false},
      {id: 'dm.4.4', name: 'Group Theory', weight: 33, completed: false},
      {id: 'dm.4.5', name: 'Lattice', weight: 9, completed: false},
      {id: 'dm.4.6', name: 'Mathematical Induction', weight: 2, completed: false},
      {id: 'dm.4.7', name: 'Number Theory', weight: 7, completed: false},
      {id: 'dm.4.8', name: 'Partial Order', weight: 11, completed: false},
      {id: 'dm.4.9', name: 'Polynomials', weight: 4, completed: false},
      {id: 'dm.4.10', name: 'Relations', weight: 36, completed: false},
      {id: 'dm.4.11', name: 'Set Theory', weight: 27, completed: false},
    ]
  },
  {
    id: 'engineering-mathematics',
    name: 'Engineering Mathematics',
    totalWeight: 225,
    topics: [
      {id: 'em.5.1', name: 'Continuity', weight: 8, completed: false},
      {id: 'em.5.2', name: 'Definite Integral', weight: 2, completed: false},
      {id: 'em.5.3', name: 'Differentiation', weight: 6, completed: false},
      {id: 'em.5.4', name: 'Integration', weight: 11, completed: false},
      {id: 'em.5.5', name: 'Limits', weight: 13, completed: false},
      {id: 'em.5.6', name: 'Maxima Minima', weight: 10, completed: false},
      {id: 'em.5.7', name: 'Polynomials', weight: 2, completed: false},
      {id: 'em.6.1', name: 'Cartesian Coordinates', weight: 1, completed: false},
      {id: 'em.6.2', name: 'Determinant', weight: 10, completed: false},
      {id: 'em.6.3', name: 'Eigen Value', weight: 31, completed: false},
      {id: 'em.6.4', name: 'Matrix', weight: 19, completed: false},
      {id: 'em.6.5', name: 'Rank of Matrix', weight: 6, completed: false},
      {id: 'em.6.6', name: 'System of Equations', weight: 14, completed: false},
      {id: 'em.6.7', name: 'Vector Space', weight: 4, completed: false},
      {id: 'em.7.1', name: 'Binomial Distribution', weight: 6, completed: false},
      {id: 'em.7.2', name: 'Conditional Probability', weight: 14, completed: false},
      {id: 'em.7.3', name: 'Continuous Distribution', weight: 1, completed: false},
      {id: 'em.7.4', name: 'Expectation', weight: 10, completed: false},
      {id: 'em.7.5', name: 'Exponential Distribution', weight: 3, completed: false},
      {id: 'em.7.6', name: 'Independent Events', weight: 5, completed: false},
      {id: 'em.7.7', name: 'Normal Distribution', weight: 2, completed: false},
      {id: 'em.7.8', name: 'Poisson Distribution', weight: 4, completed: false},
      {id: 'em.7.9', name: 'Probability', weight: 26, completed: false},
      {id: 'em.7.10', name: 'Probability Density Function', weight: 1, completed: false},
      {id: 'em.7.11', name: 'Random Variable', weight: 5, completed: false},
      {id: 'em.7.12', name: 'Statistics', weight: 2, completed: false},
      {id: 'em.7.13', name: 'Uniform Distribution', weight: 9, completed: false},
    ]
  },
  {
    id: 'general-aptitude',
    name: 'General Aptitude',
    totalWeight: 1028,
    topics: [
        {id: 'ga.8.1', name: 'Age Relation', weight: 2, completed: false},
        {id: 'ga.8.2', name: 'Code Words', weight: 5, completed: false},
        {id: 'ga.8.3', name: 'Counting Figure', weight: 1, completed: false},
        {id: 'ga.8.4', name: 'Direction Sense', weight: 11, completed: false},
        {id: 'ga.8.5', name: 'Family Relationship', weight: 6, completed: false},
        {id: 'ga.8.6', name: 'Inequality', weight: 1, completed: false},
        {id: 'ga.8.7', name: 'Logical Reasoning', weight: 40, completed: false},
        {id: 'ga.8.8', name: 'Number Relations', weight: 3, completed: false},
        {id: 'ga.8.9', name: 'Odd One', weight: 6, completed: false},
        {id: 'ga.8.10', name: 'Passage Reading', weight: 5, completed: false},
        {id: 'ga.8.11', name: 'Round Table Arrangement', weight: 6, completed: false},
        {id: 'ga.8.12', name: 'Seating Arrangement', weight: 4, completed: false},
        {id: 'ga.8.13', name: 'Sequence Series', weight: 12, completed: false},
        {id: 'ga.8.14', name: 'Statements Follow', weight: 33, completed: false},
        {id: 'ga.9.1', name: 'Absolute Value', weight: 7, completed: false},
        {id: 'ga.9.2', name: 'Age Relation (Quant)', weight: 1, completed: false},
        {id: 'ga.9.3', name: 'Algebra', weight: 6, completed: false},
        {id: 'ga.9.4', name: 'Alligation Mixture', weight: 3, completed: false},
        {id: 'ga.9.5', name: 'Area', weight: 3, completed: false},
        {id: 'ga.9.6', name: 'Arithmetic Series', weight: 9, completed: false},
        {id: 'ga.9.7', name: 'Average', weight: 2, completed: false},
        {id: 'ga.9.8', name: 'Bar Graph', weight: 17, completed: false},
        {id: 'ga.9.9', name: 'Calendar', weight: 2, completed: false},
        {id: 'ga.9.10', name: 'Cartesian Coordinates', weight: 10, completed: false},
        {id: 'ga.9.11', name: 'Circle', weight: 5, completed: false},
        {id: 'ga.9.12', name: 'Clock Time', weight: 10, completed: false},
        {id: 'ga.9.13', name: 'Combinatory', weight: 12, completed: false},
        {id: 'ga.9.14', name: 'Compound Interest', weight: 5, completed: false},
        {id: 'ga.9.15', name: 'Conditional Probability', weight: 6, completed: false},
        {id: 'ga.9.16', name: 'Cones', weight: 1, completed: false},
        {id: 'ga.9.17', name: 'Contour Plots', weight: 4, completed: false},
        {id: 'ga.9.18', name: 'Cost Market Price', weight: 6, completed: false},
        {id: 'ga.9.19', name: 'Counting', weight: 6, completed: false},
        {id: 'ga.9.20', name: 'Cube', weight: 2, completed: false},
        {id: 'ga.9.21', name: 'Currency Notes', weight: 1, completed: false},
        {id: 'ga.9.22', name: 'Curves', weight: 2, completed: false},
        {id: 'ga.9.23', name: 'Data Interpretation', weight: 4, completed: false},
        {id: 'ga.9.24', name: 'Factors', weight: 4, completed: false},
        {id: 'ga.9.25', name: 'Fractions', weight: 4, completed: false},
        {id: 'ga.9.26', name: 'Functions', weight: 18, completed: false},
        {id: 'ga.9.27', name: 'Geometry', weight: 26, completed: false},
        {id: 'ga.9.28', name: 'Graph Coloring', weight: 1, completed: false},
        {id: 'ga.9.29', name: 'Inequality (Quant)', weight: 4, completed: false},
        {id: 'ga.9.30', name: 'LCM HCF', weight: 1, completed: false},
        {id: 'ga.9.31', name: 'Line Graph', weight: 12, completed: false},
        {id: 'ga.9.32', name: 'Lines', weight: 1, completed: false},
        {id: 'ga.9.33', name: 'Logarithms', weight: 14, completed: false},
        {id: 'ga.9.34', name: 'Maxima Minima', weight: 4, completed: false},
        {id: 'ga.9.35', name: 'Modular Arithmetic', weight: 2, completed: false},
        {id: 'ga.9.36', name: 'Number Series', weight: 10, completed: false},
        {id: 'ga.9.37', name: 'Number System', weight: 7, completed: false},
        {id: 'ga.9.38', name: 'Number Theory', weight: 6, completed: false},
        {id: 'ga.9.39', name: 'Numerical Computation', weight: 14, completed: false},
        {id: 'ga.9.40', name: 'Percentage', weight: 21, completed: false},
        {id: 'ga.9.41', name: 'Permutation and Combination', weight: 3, completed: false},
        {id: 'ga.9.42', name: 'Pie Chart', weight: 16, completed: false},
        {id: 'ga.9.43', name: 'Polynomials', weight: 4, completed: false},
        {id: 'ga.9.44', name: 'Probability', weight: 28, completed: false},
        {id: 'ga.9.45', name: 'Probability Density Function', weight: 1, completed: false},
        {id: 'ga.9.46', name: 'Profit Loss', weight: 6, completed: false},
        {id: 'ga.9.47', name: 'Quadratic Equations', weight: 11, completed: false},
        {id: 'ga.9.48', name: 'Radar Chart', weight: 1, completed: false},
        {id: 'ga.9.49', name: 'Ratio Proportion', weight: 26, completed: false},
        {id: 'ga.9.50', name: 'Scatter Plot', weight: 1, completed: false},
        {id: 'ga.9.51', name: 'Seating Arrangement (Quant)', weight: 4, completed: false},
        {id: 'ga.9.52', name: 'Sequence Series (Quant)', weight: 10, completed: false},
        {id: 'ga.9.53', name: 'Set Theory', weight: 1, completed: false},
        {id: 'ga.9.54', name: 'Speed Time Distance', weight: 19, completed: false},
        {id: 'ga.9.55', name: 'Squares', weight: 4, completed: false},
        {id: 'ga.9.56', name: 'Statistics', weight: 9, completed: false},
        {id: 'ga.9.57', name: 'System of Equations', weight: 1, completed: false},
        {id: 'ga.9.58', name: 'Tabular Data', weight: 10, completed: false},
        {id: 'ga.9.59', name: 'Triangles', weight: 11, completed: false},
        {id: 'ga.9.60', name: 'Trigonometry', weight: 1, completed: false},
        {id: 'ga.9.61', name: 'Unit Digit', weight: 2, completed: false},
        {id: 'ga.9.62', name: 'Venn Diagram', weight: 16, completed: false},
        {id: 'ga.9.63', name: 'Volume', weight: 2, completed: false},
        {id: 'ga.9.64', name: 'Work Time', weight: 17, completed: false},
        {id: 'ga.10.1', name: 'Assembling Pieces', weight: 4, completed: false},
        {id: 'ga.10.2', name: 'Counting Figure (Spatial)', weight: 1, completed: false},
        {id: 'ga.10.3', name: 'Grouping', weight: 1, completed: false},
        {id: 'ga.10.4', name: 'Image Rotation', weight: 7, completed: false},
        {id: 'ga.10.5', name: 'Mirror Image', weight: 7, completed: false},
        {id: 'ga.10.6', name: 'Paper Folding', weight: 10, completed: false},
        {id: 'ga.10.7', name: 'Patterns In Three Dimensions', weight: 8, completed: false},
        {id: 'ga.10.8', name: 'Patterns In Two Dimensions', weight: 9, completed: false},
        {id: 'ga.11.1', name: 'Articles', weight: 1, completed: false},
        {id: 'ga.11.2', name: 'Comparative Forms', weight: 7, completed: false},
        {id: 'ga.11.3', name: 'English Grammar', weight: 12, completed: false},
        {id: 'ga.11.4', name: 'Grammatical Error', weight: 9, completed: false},
        {id: 'ga.11.5', name: 'Incorrect Sentence Part', weight: 5, completed: false},
        {id: 'ga.11.6', name: 'Most Appropriate Word', weight: 110, completed: false},
        {id: 'ga.11.7', name: 'Noun Verb Adjective', weight: 3, completed: false},
        {id: 'ga.11.8', name: 'Opposite', weight: 5, completed: false},
        {id: 'ga.11.9', name: 'Passage Reading (Verbal)', weight: 56, completed: false},
        {id: 'ga.11.10', name: 'Phrasal Verb', weight: 2, completed: false},
        {id: 'ga.11.11', name: 'Phrase Meaning', weight: 8, completed: false},
        {id: 'ga.11.12', name: 'Prepositions', weight: 8, completed: false},
        {id: 'ga.11.13', name: 'Pronouns', weight: 4, completed: false},
        {id: 'ga.11.14', name: 'Sentence Ordering', weight: 5, completed: false},
        {id: 'ga.11.15', name: 'Statement Sufficiency', weight: 2, completed: false},
        {id: 'ga.11.16', name: 'Statements Follow (Verbal)', weight: 2, completed: false},
        {id: 'ga.11.17', name: 'Synonyms', weight: 19, completed: false},
        {id: 'ga.11.18', name: 'Tenses', weight: 24, completed: false},
        {id: 'ga.11.19', name: 'Verbal Reasoning', weight: 40, completed: false},
        {id: 'ga.11.20', name: 'Word Meaning', weight: 17, completed: false},
        {id: 'ga.11.21', name: 'Word Pairs', weight: 29, completed: false},
    ]
  },
];
